# Generated by Django 6.0.5 on 2026-05-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_property_image_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='license_back',
            field=models.ImageField(blank=True, null=True, upload_to='agent_docs/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='license_front',
            field=models.ImageField(blank=True, null=True, upload_to='agent_docs/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='national_id_back',
            field=models.ImageField(blank=True, null=True, upload_to='agent_docs/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='national_id_front',
            field=models.ImageField(blank=True, null=True, upload_to='agent_docs/'),
        ),
    ]
