# Generated by Django 6.0.5 on 2026-05-15 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_property_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RemoveField(
            model_name='property',
            name='views',
        ),
    ]
