# Generated by Django 6.0.5 on 2026-05-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_is_active_property_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
