# Generated by Django 6.0.5 on 2026-05-15 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_property_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='active',
            new_name='is_active',
        ),
    ]
