# Generated by Django 6.0.5 on 2026-05-15 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_active_property_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='is_active',
        ),
    ]
