# Generated by Django 6.0.5 on 2026-05-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_property_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Published', 'Published'), ('Rejected', 'Rejected'), ('Inactive', 'Inactive')], default='Pending', max_length=20),
        ),
    ]
