# Generated by Django 6.0.5 on 2026-06-19 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('promotion_type', models.CharField(choices=[('banner', 'Banner'), ('featured', 'Featured Listing'), ('discount', 'Discount'), ('announcement', 'Announcement')], default='announcement', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='promotions/')),
                ('link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
