# Generated by Django 6.0.5 on 2026-06-19 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_promotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='link',
        ),
        migrations.AddField(
            model_name='promotion',
            name='discount_text',
            field=models.CharField(blank=True, help_text='e.g. Save Up To 15%', max_length=50),
        ),
        migrations.AddField(
            model_name='promotion',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='accounts.property'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promotion_type',
            field=models.CharField(choices=[('banner', 'Banner'), ('featured', 'Featured Listing'), ('discount', 'Discount'), ('announcement', 'Announcement')], default='featured', max_length=20),
        ),
    ]
