# Generated by Django 6.0.5 on 2026-06-19 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_promotion_link_promotion_discount_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='agent_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='promotion',
            name='bathrooms',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='promotion',
            name='bedrooms',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='promotion',
            name='caption_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='caption_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='caption_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='caption_4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='promotions/'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='promotions/'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='promotions/'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='promotion',
            name='price',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='property_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='promotion',
            name='property_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='promotion',
            name='square_meters',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='accounts.property'),
        ),
    ]
