# Generated by Django 6.0.5 on 2026-06-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_promotion_agent_phone_promotion_bathrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
