databases:
  - name: delala
    databaseName: delala_gutg
    plan: free

services:
  - type: web
    name: digital-delala
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn your_project_name.wsgi:application

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: delala
          property: connectionString

      - key: DJANGO_SETTINGS_MODULE
        value: your_project_name.settings

      - key: DEBUG
        value: "False"
